/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.basesdedatoseps;

import Clases.CredencialesFijas;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Karol
 */
public class IniciarSesion extends javax.swing.JFrame {
    

    /**
     * Creates new form IniciarSesion
     */
    public IniciarSesion() {
        initComponents();
        this.setLocationRelativeTo(this);
        setImageLabel(Logo, "src/main/java/Imagenes/Logo.png");
        setImageLabel(jLabel1, "src/main/java/Imagenes/Lateral.jpg");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DesplegableUsuarios = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        PassTxt = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(2147483647, 4));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 0, 350, 500));
        jPanel2.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 140, 130));

        Title.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        Title.setText("INICIAR SESIÓN");
        jPanel2.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setText("ELIJA SU PERFIL");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 160, 30));

        DesplegableUsuarios.setFont(new java.awt.Font("SansSerif", 0, 17)); // NOI18N
        DesplegableUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COTIZANTE", "ADMINISTRADOR", "BANCO" }));
        DesplegableUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesplegableUsuariosActionPerformed(evt);
            }
        });
        jPanel2.add(DesplegableUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 200, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setText("CONTRASEÑA");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 160, -1));

        userTxt.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        userTxt.setForeground(new java.awt.Color(153, 153, 153));
        userTxt.setText("Ingrese su DI");
        userTxt.setBorder(null);
        userTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userTxtMousePressed(evt);
            }
        });
        userTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxtActionPerformed(evt);
            }
        });
        jPanel2.add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 320, -1));

        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jSeparator1.setMaximumSize(new java.awt.Dimension(32767, 10000));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 320, 10));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setText("USUARIO");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 130, -1));

        PassTxt.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        PassTxt.setForeground(new java.awt.Color(204, 204, 204));
        PassTxt.setText("**********");
        PassTxt.setBorder(null);
        PassTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PassTxtMousePressed(evt);
            }
        });
        PassTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassTxtActionPerformed(evt);
            }
        });
        jPanel2.add(PassTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 320, -1));

        jSeparator2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jSeparator2.setMaximumSize(new java.awt.Dimension(32767, 10000));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 320, -1));

        jPanel1.setBackground(new java.awt.Color(45, 98, 138));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ENTRAR");
        jLabel7.setToolTipText("");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DesplegableUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesplegableUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DesplegableUsuariosActionPerformed

    private void userTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxtActionPerformed

    }//GEN-LAST:event_userTxtActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        String usuarioSeleccionado = (String) DesplegableUsuarios.getSelectedItem();

        String di = userTxt.getText();
        String contrasena = new String(PassTxt.getPassword());

        Coneccion conexion = new Coneccion();
        boolean esValido = false;

        switch (usuarioSeleccionado) {
            case "ADMINISTRADOR":
                esValido = CredencialesFijas.validarAdministrador(di, contrasena);
                if (esValido) {
                    VentanaAdministrador adminWindow = new VentanaAdministrador();
                    adminWindow.setVisible(true);
                    this.setVisible(false);
                    adminWindow.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            setVisible(true);
                        }
                    });
                }
                break;

            case "BANCO":
                esValido = CredencialesFijas.validarBanco(di, contrasena);
                if (esValido) {
                    Banco bancoWindow = new Banco();
                    bancoWindow.setVisible(true);
                    this.setVisible(false);
                    bancoWindow.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            setVisible(true);
                        }
                    });
                }
                break;

            case "COTIZANTE":
                    conexion.conectar();
                    esValido = conexion.validarCredencialesCotizantes(di, contrasena); // contrasena = Telefono
                    if (esValido) {
                        VentanaCotizante cotizanteWindow = new VentanaCotizante();
                        cotizanteWindow.setVisible(true);
                        this.setVisible(false);
                        cotizanteWindow.addWindowListener(new java.awt.event.WindowAdapter() {
                            @Override
                            public void windowClosing(java.awt.event.WindowEvent e) {
                                setVisible(true);
                            }
                        });
                    }
                    break;

            default:
                JOptionPane.showMessageDialog(this, "Tipo de usuario no válido", "Error", JOptionPane.ERROR_MESSAGE);
        }

        if (!esValido) {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited

    }//GEN-LAST:event_jLabel7MouseExited

    private void userTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTxtMousePressed
        if (userTxt.getText().equals("Ingrese su ID")){
            userTxt.setText("");
            userTxt.setForeground(Color.black);
        }
        
        if (String.valueOf(PassTxt.getPassword()).isEmpty()){
            PassTxt.setText("**********");
            PassTxt.setForeground(Color.gray);
        }
    }//GEN-LAST:event_userTxtMousePressed

    private void PassTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassTxtMousePressed
        if (String.valueOf(PassTxt.getPassword()).equals("**********")){
            PassTxt.setText("");
            PassTxt.setForeground(Color.black);
        }
        if (userTxt.getText().isEmpty()){
            userTxt.setText("Ingrese su DI");
            userTxt.setForeground(Color.gray);
        }
        
        
    }//GEN-LAST:event_PassTxtMousePressed

    private void PassTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassTxtActionPerformed
    
    private void setImageLabel(JLabel labelImage, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
            image.getImage().getScaledInstance(labelImage.getWidth(), labelImage.getHeight(), Image.SCALE_DEFAULT));
            labelImage.setIcon(icon);
            this.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DesplegableUsuarios;
    private javax.swing.JLabel Logo;
    private javax.swing.JPasswordField PassTxt;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
